### ISSUE TITLE
Config flow could not be loaded

### ISSUE THREAD

**Issue by fted** [burnnat/ha-polar#14]
After setting up the AccessLink as described and adding to the config i get the following when adding the polar integration.
"Config flow could not be loaded"

<img width="475" alt="Screenshot 2021-03-16 at 11 28 25" src="https://user-images.githubusercontent.com/39265743/111294698-e1448c80-864a-11eb-8ecc-cd37b1007923.png">

Running: core-2021.3.1 & supervisor-2021.03.6
Seems to be related to the depreciated base_url?
**I see the following error in the log at startup:**

------------------------------------------------------------------------

Logger: homeassistant
Source: custom_components/polar/config_flow.py:26
First occurred: 11:57:18 AM (1 occurrences)
Last logged: 11:57:18 AM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 133, in async_init
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 216, in _async_handle_step
    result: Dict = await getattr(flow, method)(user_input)
  File "/config/custom_components/polar/config_flow.py", line 66, in async_step_import
    return await self.async_step_client(user_input)
  File "/config/custom_components/polar/config_flow.py", line 74, in async_step_client
    return await self.async_step_oauth()
  File "/config/custom_components/polar/config_flow.py", line 94, in async_step_oauth
    url=self.accesslink.get_authorization_url(state=self.flow_id)
  File "/config/custom_components/polar/config_flow.py", line 44, in accesslink
    callback_url = setup_oauth_callback(self.hass)
  File "/config/custom_components/polar/config_flow.py", line 26, in setup_oauth_callback
    callback_url = f"{hass.config.api.base_url}{AUTH_CALLBACK_PATH}"
AttributeError: 'ApiConfig' object has no attribute 'base_url'

------------------------------------------------------------------------

Any ideas?

**Comment by fted** [comment]
I see it was solved by [jualfoar](https://github.com/jualfoar) by changing **api.base_url** for **external_url** in [this request](https://github.com/burnnat/ha-polar/pull/12).
